using System;
using System.Collections.Generic;

namespace Core.Entities
{
    public partial class Abroidatum
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public int Abid { get; set; }
        public string Ph9code { get; set; }
        public string Ph9name { get; set; }
        public bool? IsRoi { get; set; }
        public int EvaluationTypeId { get; set; }
        public decimal BaseJanuary { get; set; }
        public decimal BaseFebruary { get; set; }
        public decimal BaseMarch { get; set; }
        public decimal BaseApril { get; set; }
        public decimal BaseMay { get; set; }
        public decimal BaseJune { get; set; }
        public decimal BaseJuly { get; set; }
        public decimal BaseAugust { get; set; }
        public decimal BaseSeptember { get; set; }
        public decimal BaseOctober { get; set; }
        public decimal BaseNovember { get; set; }
        public decimal BaseDecember { get; set; }
        public decimal BaseTotal { get; set; }
        public decimal VolumeJanuary { get; set; }
        public decimal VolumeFebruary { get; set; }
        public decimal VolumeMarch { get; set; }
        public decimal VolumeApril { get; set; }
        public decimal VolumeMay { get; set; }
        public decimal VolumeJune { get; set; }
        public decimal VolumeJuly { get; set; }
        public decimal VolumeAugust { get; set; }
        public decimal VolumeSeptember { get; set; }
        public decimal VolumeOctober { get; set; }
        public decimal VolumeNovember { get; set; }
        public decimal VolumeDecember { get; set; }
        public decimal VolumeTotal { get; set; }
        public decimal Gsvjanuary { get; set; }
        public decimal Gsvfebruary { get; set; }
        public decimal Gsvmarch { get; set; }
        public decimal Gsvapril { get; set; }
        public decimal Gsvmay { get; set; }
        public decimal Gsvjune { get; set; }
        public decimal Gsvjuly { get; set; }
        public decimal Gsvaugust { get; set; }
        public decimal Gsvseptember { get; set; }
        public decimal Gsvoctober { get; set; }
        public decimal Gsvnovember { get; set; }
        public decimal Gsvdecember { get; set; }
        public decimal Gsvtotal { get; set; }
        public decimal Gpjanuary { get; set; }
        public decimal Gpfebruary { get; set; }
        public decimal Gpmarch { get; set; }
        public decimal Gpapril { get; set; }
        public decimal Gpmay { get; set; }
        public decimal Gpjune { get; set; }
        public decimal Gpjuly { get; set; }
        public decimal Gpaugust { get; set; }
        public decimal Gpseptember { get; set; }
        public decimal Gpoctober { get; set; }
        public decimal Gpnovember { get; set; }
        public decimal Gpdecember { get; set; }
        public decimal Gptotal { get; set; }
        public decimal Ttsjanuary { get; set; }
        public decimal Ttsfebruary { get; set; }
        public decimal Ttsmarch { get; set; }
        public decimal Ttsapril { get; set; }
        public decimal Ttsmay { get; set; }
        public decimal Ttsjune { get; set; }
        public decimal Ttsjuly { get; set; }
        public decimal Ttsaugust { get; set; }
        public decimal Ttsseptember { get; set; }
        public decimal Ttsoctober { get; set; }
        public decimal Ttsnovember { get; set; }
        public decimal Ttsdecember { get; set; }
        public decimal Ttstotal { get; set; }
        public decimal InvestmentJanuary { get; set; }
        public decimal InvestmentFebruary { get; set; }
        public decimal InvestmentMarch { get; set; }
        public decimal InvestmentApril { get; set; }
        public decimal InvestmentMay { get; set; }
        public decimal InvestmentJune { get; set; }
        public decimal InvestmentJuly { get; set; }
        public decimal InvestmentAugust { get; set; }
        public decimal InvestmentSeptember { get; set; }
        public decimal InvestmentOctober { get; set; }
        public decimal InvestmentNovember { get; set; }
        public decimal InvestmentDecember { get; set; }
        public decimal InvestmentTotal { get; set; }
        public decimal IncrementalGpjanuary { get; set; }
        public decimal IncrementalGpfebruary { get; set; }
        public decimal IncrementalGpmarch { get; set; }
        public decimal IncrementalGpapril { get; set; }
        public decimal IncrementalGpmay { get; set; }
        public decimal IncrementalGpjune { get; set; }
        public decimal IncrementalGpjuly { get; set; }
        public decimal IncrementalGpaugust { get; set; }
        public decimal IncrementalGpseptember { get; set; }
        public decimal IncrementalGpoctober { get; set; }
        public decimal IncrementalGpnovember { get; set; }
        public decimal IncrementalGpdecember { get; set; }
        public decimal IncrementalGptotal { get; set; }
        public decimal Roijanuary { get; set; }
        public decimal Roifebruary { get; set; }
        public decimal Roimarch { get; set; }
        public decimal Roiapril { get; set; }
        public decimal Roimay { get; set; }
        public decimal Roijune { get; set; }
        public decimal Roijuly { get; set; }
        public decimal Roiaugust { get; set; }
        public decimal Roiseptember { get; set; }
        public decimal Roioctober { get; set; }
        public decimal Roinovember { get; set; }
        public decimal Roidecember { get; set; }
        public decimal Roitotal { get; set; }
        public decimal Gpmt { get; set; }
        public decimal AllocationRule { get; set; }
        public string Justification { get; set; }
        public bool IsPostMonth { get; set; }
    }
}
