using System;
using System.Collections.Generic;

namespace Core.Entities
{
    public partial class Ddclaim
    {
        public string SeperatorForNewDocument { get; set; }
        public string DocumentDate { get; set; }
        public string DocumentType { get; set; }
        public string CompanyCode { get; set; }
        public string ProcessedDate { get; set; }
        public int? Period { get; set; }
        public string CurrencyKey { get; set; }
        public string ExchangeRate { get; set; }
        public string Reference { get; set; }
        public string DocumentHeader { get; set; }
        public string PostingKey { get; set; }
        public string Account { get; set; }
        public decimal? AmountInDocumentCurrency { get; set; }
        public string Empty14 { get; set; }
        public string Empty15 { get; set; }
        public string Empty16 { get; set; }
        public string EmptyQ17 { get; set; }
        public string EmptyR18 { get; set; }
        public string EmptyS19 { get; set; }
        public string ItemText { get; set; }
        public string EmptyU21 { get; set; }
        public string EmptyV22 { get; set; }
        public string EmptyW23 { get; set; }
        public string EmptyX24 { get; set; }
        public string EmptyY25 { get; set; }
        public string EmptyZ26 { get; set; }
        public string EmptyAa27 { get; set; }
        public string EmptyAb28 { get; set; }
        public string Empty29 { get; set; }
        public string Empty30 { get; set; }
        public string Empty31 { get; set; }
        public string Empty32 { get; set; }
        public string Empty33 { get; set; }
        public string Empty34 { get; set; }
        public string Empty35 { get; set; }
        public string Empty36 { get; set; }
        public string Empty37 { get; set; }
        public string Empty38 { get; set; }
        public string Empty39 { get; set; }
        public string Empty40 { get; set; }
        public string Empty41 { get; set; }
        public string Empty42 { get; set; }
        public string Empty43 { get; set; }
        public string Empty44 { get; set; }
        public string Empty45 { get; set; }
        public string Empty46 { get; set; }
        public string Empty47 { get; set; }
        public string Empty48 { get; set; }
        public string Empty49 { get; set; }
        public string Empty50 { get; set; }
        public string Empty51 { get; set; }
        public string Empty52 { get; set; }
        public string Empty53 { get; set; }
        public string Empty54 { get; set; }
        public string Empty55 { get; set; }
        public string Empty56 { get; set; }
        public string Empty57 { get; set; }
        public string Empty58 { get; set; }
        public string Empty59 { get; set; }
        public string Empty60 { get; set; }
        public string Empty61 { get; set; }
        public string Empty62 { get; set; }
        public string Empty63 { get; set; }
        public string Empty64 { get; set; }
        public string Empty65 { get; set; }
        public string Empty66 { get; set; }
        public string Empty67 { get; set; }
        public string Empty68 { get; set; }
        public string Empty69 { get; set; }
        public string Empty70 { get; set; }
        public string Empty71 { get; set; }
        public string Empty72 { get; set; }
        public string Empty73 { get; set; }
        public string Empty74 { get; set; }
        public string Empty75 { get; set; }
        public string Empty76 { get; set; }
        public string Empty77 { get; set; }
        public string Empty78 { get; set; }
        public string Empty79 { get; set; }
        public string Empty80 { get; set; }
        public string Empty81 { get; set; }
        public string Empty82 { get; set; }
        public string Empty83 { get; set; }
        public string Empty84 { get; set; }
        public string Empty85 { get; set; }
        public string Empty86 { get; set; }
        public string Empty87 { get; set; }
        public string Empty88 { get; set; }
        public string Empty89 { get; set; }
        public string Empty90 { get; set; }
        public string Empty91 { get; set; }
        public string Empty92 { get; set; }
        public string Empty93 { get; set; }
        public string Empty94 { get; set; }
        public string Empty95 { get; set; }
        public string Empty96 { get; set; }
        public string Empty97 { get; set; }
        public string Empty98 { get; set; }
        public string Empty99 { get; set; }
        public string Empty100 { get; set; }
        public string Empty101 { get; set; }
        public string Empty102 { get; set; }
        public string Empty103 { get; set; }
        public string Empty104 { get; set; }
        public string Empty105 { get; set; }
        public string Empty106 { get; set; }
        public string Empty107 { get; set; }
        public string Empty108 { get; set; }
        public string Empty109 { get; set; }
        public string Empty110 { get; set; }
        public string Empty111 { get; set; }
        public string Empty112 { get; set; }
        public string Empty113 { get; set; }
        public string Empty114 { get; set; }
        public string Empty115 { get; set; }
        public string Empty116 { get; set; }
        public string Empty117 { get; set; }
        public string Empty118 { get; set; }
        public string Empty119 { get; set; }
        public string Empty120 { get; set; }
        public string Empty121 { get; set; }
        public string Empty122 { get; set; }
        public string Empty123 { get; set; }
        public string Empty124 { get; set; }
        public string Empty125 { get; set; }
        public string Empty126 { get; set; }
        public string Empty127 { get; set; }
        public string Empty128 { get; set; }
        public string Empty129 { get; set; }
        public string Empty130 { get; set; }
        public string Empty131 { get; set; }
        public string Empty132 { get; set; }
    }
}
