using System;
using System.Collections.Generic;

namespace Core.Entities
{
    public partial class ThisSystem
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public decimal Vat { get; set; }
        public decimal Ait { get; set; }
        public decimal AbabsoluteValue { get; set; }
        public int AgencyCommission { get; set; }
        public int DefaultReviewUserId { get; set; }
        public decimal Omlimit { get; set; }
        public int OmexpTypeId { get; set; }
        public string Currency { get; set; }
        public bool CanActivateLimit { get; set; }
        public bool CanOneAthoUser { get; set; }
        public bool CanPromtAbs { get; set; }
        public string MsgForAll { get; set; }
        public DateTime? ChgPayStDt { get; set; }
        public DateTime? ChgPayEnDt { get; set; }
        public string Iotype { get; set; }
        public string CompanyCode { get; set; }
        public string ExternalOrderNumber { get; set; }
        public string ControllingArea { get; set; }
        public string IdentifiesForStatisticalOrders { get; set; }
        public string SalesDocumentType { get; set; }
        public string Division { get; set; }
        public string DistributionChannel { get; set; }
        public string TargetQuantity { get; set; }
        public string CurrencyCode { get; set; }
        public string CompanyProfitCentre { get; set; }
        public string CostElement { get; set; }
        public string ChargeDocumentType { get; set; }
        public string ChargePostingKey { get; set; }
        public string ProvisionPostingKey { get; set; }
        public DateTime Guidate { get; set; }
        public int Guiserial { get; set; }
        public string PaymentDocumentType { get; set; }
        public string PaymentVendorPostingKey { get; set; }
        public string PaymentProvisionPostingKey { get; set; }
        public string PaymentTaxCode { get; set; }
        public string ClaimContraAccount { get; set; }
        public string Tvcommodity { get; set; }
        public string RadioCommodity { get; set; }
        public string PressCommodity { get; set; }
        public string OtherCommodity { get; set; }
        public string Tvglcode { get; set; }
        public string RadioGlcode { get; set; }
        public string PressGlcode { get; set; }
        public string DigitalGlcode { get; set; }
        public string OtherGlcode { get; set; }
        public string TvcostCenter { get; set; }
        public string RadioCostCenter { get; set; }
        public string PressCostCenter { get; set; }
        public string DigitalCostCenter { get; set; }
        public string TvserviceNumber { get; set; }
        public string RadioServiceNumber { get; set; }
        public string PressServiceNumber { get; set; }
        public string DigitalServiceNumber { get; set; }
        public int RspmeasureId { get; set; }
        public int GmmeasureId { get; set; }
        public int TmmeasureId { get; set; }
        public int VolumeMeasureId { get; set; }
        public int BmilocalMeasureId { get; set; }
        public int TurnoverMeasureId { get; set; }
        public int GpmeasureId { get; set; }
        public int GsvmeasureId { get; set; }
        public int TtsproductMeasureId { get; set; }
        public int TtspackMeasureId { get; set; }
        public int TtsplaceMeasureId { get; set; }
        public int TtspromotionMeasureId { get; set; }
        public int TtspropositionMeasureId { get; set; }
        public int TtscppmeasureId { get; set; }
        public int TtscsmeasureId { get; set; }
        public int TtsromeasureId { get; set; }
        public int TtsddmeasureId { get; set; }
        public int TtseotpaymentMeasureId { get; set; }
        public int TtseotpromptMeasureId { get; set; }
        public int TtseotefficientOrderMeasureId { get; set; }
        public decimal Aitpercentage { get; set; }
        public int WorkingDays { get; set; }
        public bool BonusCalculate { get; set; }
        public string AutoBatchProcessDay { get; set; }
        public DateTime AitlastCloseDate { get; set; }
        public string DamageAbnumber { get; set; }
        public string DamageCbt { get; set; }
        public int Mdid { get; set; }
        public bool IsNfdapproval { get; set; }
        public int AnpfollowUpUserId { get; set; }
        public int TtsfollowUpUserId { get; set; }
        public int AnpadminId { get; set; }
        public int TtsadminId { get; set; }
        public DateTime ClosingLockMonth { get; set; }
        public int TmpmeasureId { get; set; }
        public string UblscbbankAccountNo { get; set; }
        public string PaymentGlcode { get; set; }
        public string CollectionGlcode { get; set; }
        public string Nsdabnumber { get; set; }
        public string Nsdcbt { get; set; }
        public int ScenarioIdBmi { get; set; }
        public int? CompanyId { get; set; }
        public string SalesOrg { get; set; }
        public int? RetrospectiveDays { get; set; }
        public int? CeouserId { get; set; }
        public int? FduserId { get; set; }
        public int? NegativeRoiuser1 { get; set; }
        public int? NegativeRoiuser2 { get; set; }
    }
}
